### ISSUE TITLE
Cannot use --servers command line option in ngasArchiveClient

### ISSUE THREAD

**Issue by smclay** [ICRAR/ngas#38]
The python NGAS archive client application cannot use the --servers command line option value. At line 90 in ngamsPClient.py an exception is raised when the servers and host/port command line options are set. As the host and port command line values are assigned default values this means an exception will always be raised when the --servers is used.

The simple solution would be to remove the default values for the host/port command line options. Otherwise grant the servers command line option precedence when it is set.

**Comment by rtobar** [comment]
Thanks @smclay for reporting this. A fix has now been merged to the `master` branch. A new unit test ensures the `--servers` flag can be used successfully.
