### ISSUE TITLE
Move bad-files under volumes directory

### ISSUE THREAD

**Issue by smclay** [ICRAR/ngas#51]
It was suggested to me by one of the ARC system administrators that it would be better to move the `bad-files` sub-directory under the volumes directory. Similar to the staging area directory.

At the moment NGAS creates a bad-files directory `/srv/ngas1/bad-files` and the staging area directory `/srv/ngas1/volume1/staging`. It would be better for consistency if NGAS were to create the `bad-files` directory in the same volume directory as the `staging` area directory. For example, `/srv/ngas1/volume1/bad-files`.

I believe the main advantages are...

1. More consistent
2. It is easier to trace which files failed to archive from which volumes
3. It is more flexible for creating NGAS volume mount points

I believe this last point is of particular interest to our ARC colleague because they are mounting NGAS volumes on a SAN.

**Comment by smclay** [comment]
Further to my previous description I got the following feedback from our ARC colleague...

* `NGASx/bad-files` needs huge storage to store all the files under `/NGASx/volume*/staging/*` at the time stop/restart NGAS service
* `mv /NGASXX/volumeXX/staging/* /NGASXX/bad-files/` can take a long time in the case of many large files are under mirroring

If bad-files is located on each volume...
*  No additional storage is needed
* `mv /NGASXX/volumex/staging/*/NGASXX/volumeXX/bad-files/` is very fast because files are moved to same storage

And I can not find the reason of moving staging files to bad-files. I think 99.9% bad-files are not needed, just needs to delete frequently. Only good reason might be it can be used to resuming, I don't know how does NGAS github use bad-files...

**Comment by rtobar** [comment]
@smclay thanks for the suggestion. I agree with all the points, and I also don't see any particular reason for the bad-files area not to be turned into a per-volume directory. AFAIK bad-files is a sink, the system doesn't automatically promote any file out of it; files end up there only for inspection purposes I think, and here and there admins might want to register or locally archive bad-files.

Changes should be fairly simple, I'll try to work it out these days.

**Comment by smclay** [comment]
@rtobar thank you for taking care of this. I am sure Eisuke will be very happy as it will help solve his SAN storage mounting issues.

**Comment by rtobar** [comment]
@smclay I've implemented the changes in the `issue-51` branch, with the `bad-files` directory now appearing under each volume directory as discussed. Unit tests have been updated to reflect this new logic. Please test at your earliest convenience and after that I'll merge back to the `master`.

**Comment by rtobar** [comment]
Great, thanks for the info! I've merged the branch now to the `master`.

**Comment by smclay** [comment]
@rtobar I got a message from Eisuke. He reported that "Data Check thread has scanned all the files under  `*/volume*/` and files found under `bad-files` directory were reported as `NOT REGISTERED FILES`"
He suggests that "it may be useful for admin to know there is unprocessed files under `bad-files` but perhaps using another category, e.g. `BAD-FILES FOUND ON STORAGE DISKS` is better then `NOT REGISTERED FILES`
What do you think?

**Comment by rtobar** [comment]
@smclay Ahhh, that's a side effect we didn't see coming. That should not be difficult to do I think. Could you open a new issue to keep track of that separately please? Thanks!

**Comment by smclay** [comment]
OK. I create a new issue. Thanks
