### ISSUE TITLE
ngamsServer and ngamsDaemon use different PID files

### ISSUE THREAD

**Issue by smclay** [ICRAR/ngas#54]
The ngamsServer and ngamsDaemon both create PID files but with different paths. The ngamsServer has a command line option `-force` which the help description says `Force the start of the server, even if a PID file is present`. The allows us to recover from a crash. The PID file is stored at `/srv/ngas1/.aat-ngas-2:8001.pid`.
However, the ngamsDaemon does not provide any support for cleaning up bad PID files which means the user must manually delete the PID typically found at `/srv/ngas1/var/run/ngamsDaemon.pid`. This is quite inconvenient for obvious reasons.
Can the ngamsDaemon also support the `-force` command line option? This would make recovering from a crash much easier and efficient.

**Comment by rtobar** [comment]
The `-force` flag has been added in #54.
