### ISSUE TITLE
Deprecated function calls in src/ngamsCore/ngamsLib

### ISSUE THREAD

**Issue by ulange-eso-org** [ICRAR/ngas#84]
Remove deprecated threading.Thread function calls from src/ngamsCore/ngamsLib/ngamsThreadGroup.py
(found by runnning mypy on src/ngamsCore).

references:
https://docs.python.org/3/library/threading.html#thread-objects
https://github.com/spotify/luigi/issues/2939

diff --git a/src/ngamsCore/ngamsLib/ngamsThreadGroup.py b/src/ngamsCore/ngamsLib/ngamsThreadGroup.py
index c039ef73..647bfcbc 100755
```
--- a/src/ngamsCore/ngamsLib/ngamsThreadGroup.py
+++ b/src/ngamsCore/ngamsLib/ngamsThreadGroup.py
@@ -153,7 +153,7 @@ class ngamsThreadGroup:
             thrId = "%s-%d" % (id, n)
             thrObj = threading.Thread(None, self.__threadEncapsulator,
                                       thrId, args)
-            thrObj.setDaemon(0)
+            thrObj.daemon = False
             thrObj.start()
             self.__threadHandles.append(thrObj)

@@ -194,7 +194,7 @@ class ngamsThreadGroup:
         """
         activeThreads = 0
         for threadHandle in self.__threadHandles:
-            if (threadHandle.isAlive()): activeThreads += 1
+            if (threadHandle.is_alive()): activeThreads += 1
         return activeThreads


@@ -349,7 +349,7 @@ class ngamsThreadGroup:
                           "to terminate"
                     raise Exception(msg)
             thrWaitingList[0].join(curTimeout)
-            if (not thrWaitingList[0].isAlive()): del thrWaitingList[0]
+            if (not thrWaitingList[0].is_alive()): del thrWaitingList[0]
             if (thrWaitingList == []):
                 return self
```

**Comment by rtobar** [comment]
Thanks @ulange-eso-org for all the issues and patches! I'm in the process of incorporating them, most of them verbatim, although these reports have given me the chance to uncover a couple of more things.

What is the context of this work? I'm interested in the linting exercise you're doing by adding type annotations into the source code. As you mention a couple of times, I indeed can't just take these annotations in, as they would break the source code with 2.7 and we're still supporting that (but it might be worth checking again with the ALMA folks what their stand is here).

Today I wasn't at work, so there's still one or two things that I missed, but hopefully tomorrow I can close all the issues you raised. Keep them coming!

**Comment by ulange-eso-org** [comment]
Hi Rodrigo,
Context: Effort on upgrading the VLT NGAS archive to the ICRAR version is picking up here. Nathalie from Archive group while carrying out tests ran into an issue (bytes vs. string reading access codes from a NGAS RC file) that I felt should easily be uncovered by light type checking. So I set out trying if I could find the bug (I was able to do it). In the process I found more things hence all the tickets. ALMA is still planning with Python 2 and migrating to Python 3 later as far as I know.

Out of interest: How do you provide backwards compatibility? For example I see most of the code using print statements bt nowhere do I spot a 'from __future__ import print_statement' ...
Cheers, Uwe.

Details of what I did:
```
# on fresh Fedora 34 machine
mkdir icrar-ngas
cd icrar-ngas/
git clone https://github.com/ICRAR/ngas
python3 -m venv venv
. venv/bin/activate
python3 -m pip install --upgrade pip
python3 -m pip install mypy

cd ngas/src/
# create mypy config file
cat setup.cfg
[mypy]
check_untyped_defs = True
ignore_missing_imports = True

find . -maxdepth 1 -type d -name 'ngams*' -exec mypy --install-types {} \; > mypy.out
# answer with "y" when being asked to install typing stubs
# gradually refine typing annotations in Python
# files, esp. those that get imported by other packages
```

**Comment by rtobar** [comment]
@ulange-eso-org I'll close this issue as the changes have already been merged to the `master` branch, but feel free to post any further comments.
