### ISSUE TITLE
Insufficient error checks in get_db_parameters() function

### ISSUE THREAD

**Issue by ulange-eso-org** [ICRAR/ngas#92]
https://github.com/ICRAR/ngas/blob/e1f7d70a125098b8bb8cd85dea7d6c924baa554f/src/ngamsUtils/ngamsUtils/ngasUtilsLib.py#L175

This function is supposed to return a tuple of five string values. However since the resource file is written by an end user there is no guarantee that any of the parameters which `get_db_parameters()` tries to find is defined by the user. We just had the case that property `DbInterface` was not set in such rc file and it lead to a really hard to understand runtime exception when executing utility `ngas-xsync-tool`. I would argue that `get_db_parameters()` shall fail immediately with a clear error message whenever one of the properties that `get_db_parameters()` tries to read from an resource file is missing.

**Comment by rtobar** [comment]
Thanks Uwe for these reports. I've pushed fixes for all three problems in a new `uwe-fixes` branch, could you verify they are working as expected? Thanks!
